### ISSUE TITLE
I am not being able to import xlstm

### ISSUE THREAD

**Issue by sm-ak-r33** [akaashdash/xlstm#3]
I did '%pip install xlstm' yet 'from xlstm import xLSTM' is giving me 

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[15], line 7
      5 import torch.optim as optim
      6 from torch.utils.data import DataLoader, Dataset
----> 7 from xlstm import xLSTM
      9 # Define the dataset class
     10 class TimeSeriesDataset(Dataset):

ModuleNotFoundError: No module named 'xlstm'

How to fix this?

**Comment by akaashdash** [comment]
The package is `torchxlstm`. https://pypi.org/project/torchxlstm/
